// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q          = new(Query)
	TObjectTag *tObjectTag
	TTag       *tTag
	TTokenInfo *tTokenInfo
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	TObjectTag = &Q.TObjectTag
	TTag = &Q.TTag
	TTokenInfo = &Q.TTokenInfo
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:         db,
		TObjectTag: newTObjectTag(db, opts...),
		TTag:       newTTag(db, opts...),
		TTokenInfo: newTTokenInfo(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	TObjectTag tObjectTag
	TTag       tTag
	TTokenInfo tTokenInfo
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:         db,
		TObjectTag: q.TObjectTag.clone(db),
		TTag:       q.TTag.clone(db),
		TTokenInfo: q.TTokenInfo.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:         db,
		TObjectTag: q.TObjectTag.replaceDB(db),
		TTag:       q.TTag.replaceDB(db),
		TTokenInfo: q.TTokenInfo.replaceDB(db),
	}
}

type queryCtx struct {
	TObjectTag ITObjectTagDo
	TTag       ITTagDo
	TTokenInfo ITTokenInfoDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		TObjectTag: q.TObjectTag.WithContext(ctx),
		TTag:       q.TTag.WithContext(ctx),
		TTokenInfo: q.TTokenInfo.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
