// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTChainInfo = "t_chain_info"

// TChainInfo mapped from table <t_chain_info>
type TChainInfo struct {
	ID                      int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Chainid                 string    `gorm:"column:chainid;not null" json:"chainid"`
	RealChainid             string    `gorm:"column:real_chainid;not null" json:"real_chainid"`
	Name                    string    `gorm:"column:name;not null" json:"name"`
	UpdateTimestamp         time.Time `gorm:"column:update_timestamp;not null;default:CURRENT_TIMESTAMP" json:"update_timestamp"`
	InsertTimestamp         time.Time `gorm:"column:insert_timestamp;not null;default:CURRENT_TIMESTAMP" json:"insert_timestamp"`
	AliasName               string    `gorm:"column:alias_name;not null" json:"alias_name"`
	Backend                 int32     `gorm:"column:backend;not null" json:"backend"`
	Eip1559                 bool      `gorm:"column:eip1559;not null" json:"eip1559"`
	NetworkCode             int32     `gorm:"column:network_code;not null" json:"network_code"`
	BlockInterval           int32     `gorm:"column:block_interval;not null" json:"block_interval"`
	Timeout                 int32     `gorm:"column:timeout;not null;default:120" json:"timeout"`
	Icon                    string    `gorm:"column:icon;not null" json:"icon"`
	RPCEndPoint             string    `gorm:"column:rpc_end_point;not null" json:"rpc_end_point"`
	ExplorerURL             string    `gorm:"column:explorer_url;not null" json:"explorer_url"`
	GasTokenName            string    `gorm:"column:gas_token_name;not null" json:"gas_token_name"`
	GasTokenAddress         string    `gorm:"column:gas_token_address;not null" json:"gas_token_address"`
	GasTokenDecimal         int32     `gorm:"column:gas_token_decimal;not null" json:"gas_token_decimal"`
	GasTokenIcon            string    `gorm:"column:gas_token_icon;not null" json:"gas_token_icon"`
	TransferNativeGas       int32     `gorm:"column:transfer_native_gas;not null" json:"transfer_native_gas"`
	TransferErc20Gas        int32     `gorm:"column:transfer_erc20_gas;not null" json:"transfer_erc20_gas"`
	DepositGas              int32     `gorm:"column:deposit_gas" json:"deposit_gas"`
	WithdrawGas             int32     `gorm:"column:withdraw_gas" json:"withdraw_gas"`
	Layer1                  string    `gorm:"column:layer1" json:"layer1"`
	Mainnet                 string    `gorm:"column:mainnet" json:"mainnet"`
	TransferContractAddress string    `gorm:"column:transfer_contract_address" json:"transfer_contract_address"`
	Disabled                bool      `gorm:"column:disabled;not null" json:"disabled"`
	IsTestnet               bool      `gorm:"column:is_testnet;not null" json:"is_testnet"`
	OrderWeight             int32     `gorm:"column:order_weight;not null;default:1000" json:"order_weight"`
	DepositContractAddress  string    `gorm:"column:deposit_contract_address" json:"deposit_contract_address"`
	OfficialRPC             string    `gorm:"column:official_rpc;not null" json:"official_rpc"`
	OfficialBridge          string    `gorm:"column:official_bridge;not null" json:"official_bridge"`
	MevRPCURL               string    `gorm:"column:mev_rpc_url;not null" json:"mev_rpc_url"`
}

// TableName TChainInfo's table name
func (*TChainInfo) TableName() string {
	return TableNameTChainInfo
}
