// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTGappedBlock = "t_gapped_block"

// TGappedBlock mapped from table <t_gapped_block>
type TGappedBlock struct {
	Chainid         int32     `gorm:"column:chainid;primaryKey" json:"chainid"`
	Appid           int32     `gorm:"column:appid;primaryKey" json:"appid"`
	BlockNumber     int64     `gorm:"column:block_number;primaryKey" json:"block_number"`
	UpdateTimestamp time.Time `gorm:"column:update_timestamp;not null;default:CURRENT_TIMESTAMP" json:"update_timestamp"`
	InsertTimestamp time.Time `gorm:"column:insert_timestamp;not null;default:CURRENT_TIMESTAMP" json:"insert_timestamp"`
	IsProcessed     int32     `gorm:"column:is_processed;not null" json:"is_processed"`
}

// TableName TGappedBlock's table name
func (*TGappedBlock) TableName() string {
	return TableNameTGappedBlock
}
