// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTKv = "t_kv"

// TKv mapped from table <t_kv>
type TKv struct {
	Key   string `gorm:"column:key;type:varchar(255);primaryKey" json:"key"`
	Value string `gorm:"column:value;type:text" json:"value"`
}

// TableName TKv's table name
func (*TKv) TableName() string {
	return TableNameTKv
}
