// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTTransfer = "t_transfer"

// TTransfer mapped from table <t_transfer>
type TTransfer struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Chainid         int32     `gorm:"column:chainid;not null" json:"chainid"`
	FromAddress     string    `gorm:"column:from_address;not null" json:"from_address"`
	ToAddress       string    `gorm:"column:to_address;not null" json:"to_address"`
	Value           string    `gorm:"column:value;not null" json:"value"`
	IsProcessed     int32     `gorm:"column:is_processed;not null" json:"is_processed"`
	IsInvalid       int32     `gorm:"column:is_invalid;not null" json:"is_invalid"`
	UpdateTimestamp time.Time `gorm:"column:update_timestamp;not null;default:CURRENT_TIMESTAMP" json:"update_timestamp"`
	InsertTimestamp time.Time `gorm:"column:insert_timestamp;not null;default:CURRENT_TIMESTAMP" json:"insert_timestamp"`
	Hash            string    `gorm:"column:hash;not null" json:"hash"`
	SourceTable     string    `gorm:"column:source_table;not null" json:"source_table"`
	SourceItemID    int64     `gorm:"column:source_item_id;not null" json:"source_item_id"`
	TokenAddress    string    `gorm:"column:token_address;not null" json:"token_address"`
}

// TableName TTransfer's table name
func (*TTransfer) TableName() string {
	return TableNameTTransfer
}
